### ISSUE TITLE
turso kick-off

### ISSUE THREAD

**Issue by leonardobetti** [9d8dev/directory#1]
hi folks
recently downloaded the repository to create a new directory project for a side project. I've found the .env file and created a new Turso API token, but I'm struggling to understand how to connect the database fully. I’m still unsure where to locate the DATABASE_URL needed for the setup. Also, would appreciate guidance on how to create the database schema then connect to the code. If possible, could you please provide additional information or documentation to help me set up the database connection correctly? any guidance would be much appreciated.

**Comment by brijr** [comment]
Hey Leonardo, nice job finding this! 

This is still a WIP and not in ready for prod, I'll try to make some time to work on this repo this week. Thanks for showing interest.
